name: Test

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request_target: {}

jobs:
  test:
    name: Run test
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: "go.mod"
          cache: true
          cache-dependency-path: "go.sum"
      - name: Run tests
        run: |-
          go test -v ./...
